spring.application.name=employee-service

spring.datasource.url=jdbc:mysql://localhost:3306/msdemo
spring.datasource.username=root
spring.datasource.password=password

server.port=8080

# Set Your Context Path Here
server.servlet.context-path=/employee-service

logging.level.dev.learning.employee_service.client.AddressClient=DEBUG

logging.pattern.console=%d{HH:mm:ss a} %-5level [${spring.application.name}] %logger{36} - %msg%n